
version: 2


sources:
  - name: raw_gz_sales
    description: raw gaze sales data
    tables:
      - name: raw_gz_sales
        description: sales
      - name: raw_gz_product
        description: product
      - name: raw_gz_ship
        description: ship

